name: LootPlugin
main: QuarantineMC.CodeConduit.LootPlugin.Main
version: 0.0.0
author: CodeConduit
api-version: 1.16

commands:
  getlootselector:
    description: Get all the relevant items for the loot plugin.
    permission: lootFindSelector.use