name: LootPlugin
main: QuarantineMC.CodeConduit.LootPlugin.Main
version: 0.0.0
author: CodeConduit
api-version: 1.16

commands:
  lootselector:
    description: Player recieves a loot selector tool.
    permission: lootSelector.use
  lootfinder:
    description: Player recieves a loot finder tool.
    permission: lootFinder.use